
MAJOR_VERSION = 0
MINOR_VERSION = 0
REVISION = 999

VERSION = $${MAJOR_VERSION}.$${MINOR_VERSION}.$${REVISION}

DEFINES += MAJOR_VERSION=$${MAJOR_VERSION} MINOR_VERSION=$${MINOR_VERSION} REVISION=$${REVISION}
