
MAJOR_VERSION = 0
MINOR_VERSION = 0
REVISION = 999

VERSION = $${MAJOR_VERSION}.$${MINOR_VERSION}.$${REVISION}

DEFINES += \
    QT_DEPRECATED_WARNINGS \
    MAJOR_VERSION=$${MAJOR_VERSION} \
    MINOR_VERSION=$${MINOR_VERSION} \
    REVISION=$${REVISION}

QT += core network

QMAKE_CXX = mpic++
DEFINES += QT_DEPRECATED_WARNINGS

CONFIG += c++11

isEmpty($$(CUDADIR)) {
   CUDADIR = /usr/local/cuda
}
else {
   CUDADIR = $$(CUDADIR)
}

INCLUDEPATH += $${CUDADIR}/include
DEPENDPATH += $${CUDADIR}/include
